BEGIN;

CREATE TABLE newevents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eventid INTEGER NOT NULL,
    event CHAR(2) NOT NULL,
    value CHAR(8) NOT NULL,
    time INTEGER NOT NULL
);

INSERT INTO newevents (id, eventid, event, value, time) VALUES
    (33372, 70499, 'C', '01', 1679571961),
    (33373, 70500, 'I', '61', 1679571962),
    (33374, 70501, 'I', '50', 1679571962),
    (33375, 70502, 'I', '11', 1679571963),
    (33376, 70503, 'I', '31', 1679571964),
    (33377, 70504, 'I', '40', 1679571965),
    (33378, 70505, 'I', '30', 1679571965),
    (33379, 70506, 'I', '21', 1679571966),
    (33380, 70507, 'C', '00', 1679571966),
    (33381, 70508, 'C', '11', 1679571970),
    (33382, 70509, 'I', '20', 1679571970),
    (33383, 70510, 'I', '31', 1679571970),
    (33384, 70511, 'I', '30', 1679571973),
    (33385, 70512, 'I', '41', 1679571973),
    (33386, 70513, 'I', '10', 1679571974),
    (33387, 70514, 'I', '60', 1679571974),
    (33388, 70515, 'I', '51', 1679571974),
    (33389, 70516, 'C', '10', 1679571975);

-- Continue automatically generated IDs after the imported data.
SELECT setval(
    pg_get_serial_sequence('newevents', 'id'),
    (SELECT MAX(id) FROM newevents)
);

COMMIT;