BEGIN;

CREATE TABLE liikennevalot_nodes_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id CHAR(4) NOT NULL,
    event CHAR(2) NOT NULL,
    time INTEGER,
    value CHAR(8),
    sensor CHAR(2) NOT NULL
);

INSERT INTO liikennevalot_nodes_events
    (id, node_id, event, time, value, sensor)
VALUES
    (70477, 'Home', 'I', 1679395240, '10', ''),
    (70478, 'Home', 'I', 1679395240, '60', ''),
    (70479, 'Home', 'I', 1679395241, '51', ''),
    (70480, 'Home', 'C', 1679395241, '10', ''),
    (70481, 'Home', 'C', 1679462190, '01', 'U'),
    (70482, 'Home', 'I', 1679462190, '61', ''),
    (70483, 'Home', 'I', 1679462190, '50', ''),
    (70484, 'Home', 'I', 1679462191, '11', ''),
    (70485, 'Home', 'I', 1679462192, '31', ''),
    (70486, 'Home', 'I', 1679462193, '40', ''),
    (70487, 'Home', 'I', 1679462194, '30', ''),
    (70488, 'Home', 'I', 1679462194, '21', ''),
    (70489, 'Home', 'C', 1679462194, '00', ''),
    (70490, 'Home', 'C', 1679462202, '11', ''),
    (70491, 'Home', 'I', 1679462202, '20', ''),
    (70492, 'Home', 'I', 1679462202, '31', ''),
    (70493, 'Home', 'I', 1679462205, '30', ''),
    (70494, 'Home', 'I', 1679462205, '41', ''),
    (70495, 'Home', 'I', 1679462206, '10', ''),
    (70496, 'Home', 'I', 1679462206, '60', ''),
    (70497, 'Home', 'I', 1679462206, '51', ''),
    (70498, 'Home', 'C', 1679462207, '10', ''),
    (70499, 'Home', 'C', 1679571961, '01', 'S'),
    (70500, 'Home', 'I', 1679571962, '61', ''),
    (70501, 'Home', 'I', 1679571962, '50', ''),
    (70502, 'Home', 'I', 1679571963, '11', ''),
    (70503, 'Home', 'I', 1679571964, '31', ''),
    (70504, 'Home', 'I', 1679571965, '40', ''),
    (70505, 'Home', 'I', 1679571965, '30', ''),
    (70506, 'Home', 'I', 1679571966, '21', ''),
    (70507, 'Home', 'C', 1679571966, '00', ''),
    (70508, 'Home', 'C', 1679571970, '11', ''),
    (70509, 'Home', 'I', 1679571970, '20', ''),
    (70510, 'Home', 'I', 1679571970, '31', ''),
    (70511, 'Home', 'I', 1679571973, '30', ''),
    (70512, 'Home', 'I', 1679571973, '41', ''),
    (70513, 'Home', 'I', 1679571974, '10', ''),
    (70514, 'Home', 'I', 1679571974, '60', ''),
    (70515, 'Home', 'I', 1679571974, '51', ''),
    (70516, 'Home', 'C', 1679571975, '10', '');

-- Continue automatically generated IDs after imported data.
SELECT setval(
    pg_get_serial_sequence('liikennevalot_nodes_events', 'id'),
    (SELECT MAX(id) FROM liikennevalot_nodes_events)
);


-- ---------------------------------------------------------
-- Trigger: BEFORE INSERT
--
-- If a new command event C/01 arrives, clear newevents.
-- ---------------------------------------------------------

CREATE OR REPLACE FUNCTION new_event_before()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.event = 'C' AND NEW.value = '01' THEN
        DELETE FROM newevents;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER new_event_before
BEFORE INSERT ON liikennevalot_nodes_events
FOR EACH ROW
EXECUTE FUNCTION new_event_before();


-- ---------------------------------------------------------
-- Trigger: AFTER INSERT
--
-- Copy every new event into newevents.
-- ---------------------------------------------------------

CREATE OR REPLACE FUNCTION new_event_after()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO newevents (eventid, event, value, time)
    VALUES (NEW.id, NEW.event, NEW.value, NEW.time);

    RETURN NEW;
END;
$$;

CREATE TRIGGER new_event_after
AFTER INSERT ON liikennevalot_nodes_events
FOR EACH ROW
EXECUTE FUNCTION new_event_after();

COMMIT;