BEGIN;

CREATE TABLE liikennevalot_nodes_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id VARCHAR(10) NOT NULL,
    event CHAR(2) NOT NULL,
    time INTEGER,
    value CHAR(8),
    sensor CHAR(2) NOT NULL
);

-- ---------------------------------------------------------
-- Trigger: BEFORE INSERT
--
-- If a new command event C/01 arrives, clear newevents.
-- ---------------------------------------------------------

CREATE OR REPLACE FUNCTION new_event_before()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.event = 'C' AND NEW.value = '01' THEN
        DELETE FROM newevents;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER new_event_before
BEFORE INSERT ON liikennevalot_nodes_events
FOR EACH ROW
EXECUTE FUNCTION new_event_before();


-- ---------------------------------------------------------
-- Trigger: AFTER INSERT
--
-- Copy every new event into newevents.
-- ---------------------------------------------------------

CREATE OR REPLACE FUNCTION new_event_after()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO newevents (eventid, event, value, time)
    VALUES (NEW.id, NEW.event, NEW.value, NEW.time);

    RETURN NEW;
END;
$$;

CREATE TRIGGER new_event_after
AFTER INSERT ON liikennevalot_nodes_events
FOR EACH ROW
EXECUTE FUNCTION new_event_after();

COMMIT;