BEGIN;

CREATE TABLE nodes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nodeid VARCHAR(50) NOT NULL UNIQUE,
    nodekey VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO nodes (id, nodeid, nodekey, password, created_at) VALUES
    (
        5,
        'Node2',
        'e7f6c011776e8db7cd330b54174fd76f7d0216b612387a5ffcfb81e6f0919683',
        '$2y$10$OKh.A9KicThILRWYQBILVOcJHgwsmbbc1oV2.YQVuBO86nrdKD7h.',
        '2020-03-20 12:11:34'
    );

SELECT setval(
    pg_get_serial_sequence('nodes', 'id'),
    (SELECT MAX(id) FROM nodes)
);

COMMIT;