BEGIN;

CREATE TABLE nodes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nodeid VARCHAR(50) NOT NULL UNIQUE,
    nodekey VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO nodes (id, nodeid, nodekey, password, created_at) VALUES
    (
        1,
        'Home1',
        '08dfcfc0c263d2817400a375869541c7714ed3b11ffb073902a0720eb0e47979',
        '$2y$12$5W11TWg6rFI92VDlWEzsk.uK7u9bwWUuE5Nby/RpkbSeqOI1oqICK'
    );

SELECT setval(
    pg_get_serial_sequence('nodes', 'id'),
    (SELECT MAX(id) FROM nodes)
);

COMMIT;