BEGIN;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, username, password, created_at) VALUES
    (
        1,
        'Test',
        '$2y$10$x6UdgKkkQp30jDrrvPMUxus5CAp4Z7XCaqStLAHSghWxZyAoKck11',
        '2023-03-18 11:03:50'
    );

-- MariaDB AUTO_INCREMENT was 21, so make PostgreSQL continue from 21.
SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    20,
    true
);

COMMIT;