BEGIN;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, username, password, created_at) VALUES
    (
        1,
        'Testi',
        '$2y$12$ccw0UjQ3Mmju3FEBrsGfT.VhXtcJZ64i9b.HW9ZVP3PgkPvuVM7ku',
        '2026-09-08 05:02:28.660923'
    );

-- MariaDB AUTO_INCREMENT was 21, so make PostgreSQL continue from 21.
SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    20,
    true
);

COMMIT;